services:
  postgres:
    image: postgres
    restart: always
    container_name: postgressurveydb
    environment:
      POSTGRES_DB: survey
      POSTGRES_USER: survevysa
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - survey_postgres_data:/var/lib/postgresql/data
    networks:
      - survey-network
  survey-api:
    restart: always 
    build:
      context: .
      dockerfile: ./LunavexSurveyServer/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5030:8080"
      - "5031:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=survey;Username=survevysa;Password=${POSTGRES_PASSWORD}
    networks:
      - survey-network
  survey-client:
    restart: always
    build:
      context: .
      dockerfile: ./LunavexSurveyClient/Dockerfile
    ports:
      - "5032:80"
    networks:
      - survey-network
networks:
  survey-network:
    driver: bridge


volumes:
  survey_postgres_data:
